config/routes.rb
Rails.application.routes.draw do

  get 'top/logout'
  post 'top/login'
  get 'top/index'
  
  get 'user/change'
  post 'user/update'

  get 'event/list'
  get 'event/all'
  
  post 'workpartner/tagset'
  get 'workpartner/tagset/:id',to: 'workpartner#tagset'
  get 'workpartner/list'
  get 'workpartner/new'
  get 'workpartner/delete'
  get 'workpartner/tagdelete'
  post 'workpartner/create'
  post 'workpartner/tagcreate'
  
  root 'top#main'

  resources :user
  resources :event
  resources :profile
  

end

app/controllers/top_controller.rb
class TopController < ApplicationController
    def main
        p("main start")
        if session[:login_uid]
            @events = Event.all
            redirect_to top_index_path
        else
            render 'main'
        end
    end
    
    def login
        user = User.authenticate(params[:user_address], params[:pass])
        if user
            session[:login_uid] = params[:user_address]
            flash[:notice] = "ログインできました。"
            redirect_to root_path
        else
            flash[:notice] = "ログインできませんでした。"
            redirect_to root_path
        end
    end
    
    def logout
        session.delete(:login_uid)
        p(session[:login_uid])
        redirect_to root_path
    end  

    def index
        session[:user] = User.find_by(user_address: session[:login_uid])
        Event.find_by(user_id: session[:user])
        #event_asc = Event.order(:event_day).all
        @event_asc = []
        Event.order(:event_day).all.each do |f|
          if f.user_id == session[:user][:id]
              @event_asc << f
          end
        end
        
        @workpartner = Workpartner.all
        @now = Time.current
        
        id=User.find_by(user_address: session[:login_uid]).id
        @workpartners = Workpartner.where(user_id: id)
    end
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/top/index.html.erb
<div id="head">スケジュールアプリ</div>

<hr>
<!DOCTYPE html>
<html lang="ja">
  
  <% #https://mankutsu.com/angularmaterial-sidenav-823 %>
  
<head>
  <meta charset="utf-8">
</head>

<body>


  <div class="main">
    <p>
  <h1>メインページ</h1><u><%= session[:user].user_name %>さん</u>のアカウントです。
  <div id="logout">
  <%= link_to "ログアウト", top_logout_path %><br>
  </div>
    </p>
  </div>
<%
=begin
%>
  <% if @workpartners and flash[:eventpartner] %>
    <u>
      <p><%= flash[:eventpartner] %></p>
      <p><%= link_to "新しくworkpartnerを設定", workpartner_new_path %></p>
    </u>
<%
=end
%>
  <% if flash[:notice] %>
    <u><p><%= flash[:notice] %></p></u>
  <% end %>
  

  
  



  <nav>
  <ul>
  <li><%= link_to " ホーム ", top_index_path %></li>
	<li><%= link_to " 予定作成 ", new_event_path %></li>
	<li><%= link_to " すべての予定を表示 ", event_all_path %></li>
	<li><%= link_to " プロフィール表示 ", profile_index_path %></li>
	<li><%= link_to " 消化した予定一覧 ", event_list_path %></li>
	<li><%= link_to " 仕事相手の一覧 ", workpartner_list_path %></li>
  </ul>
  </nav>
 
  <br>
  <br>
  <br>





  <hr>
  <% @event_asc.each do |f| %>
    <div id="event">
    <% if @now.ago(1.days) > f.event_day or @now.since(6.days) < f.event_day %>
    <% else %>
      <p>日付：<%= f.event_day %></p>
      <p>開催時間：<%= f.event_time.hour %>時<%= f.event_time.min %>分</p>
      <p>相手：<%= link_to "#{@workpartner.find_by(workpartner_address: f.eventpartner_address).workpartner_name}", 
                            workpartner_tagset_path(id: @workpartner.find_by(workpartner_address: f.eventpartner_address).id), 
                            method: :post %></p>
      <p>予定名：<%= f.event_title %></p>
      <p>予定内容：<%= f.event_message %></p>
      <p><div style="text-align:right"><%= link_to "予定の内容変更", edit_event_path(f) %></div></p>
      <p><div style="text-align:right"><%= link_to '削除', f, method: :delete %></div></p>
      <hr>
    <% end %>
    </div>
    <br>
  <% end %>
  
  
  <br>
  <br>
  <hr>
  <br>




</body>
</html>

app/views/top/main.html.erb
<div id="head">スケジュールアプリ</div>

<hr>
<h1>～login画面～</h1>


<% if flash[:notice] %>
  <u><p><%= flash[:notice] %></p></u>
<% end %>

<div class="login">
<p>
<h2>アカウント情報を記入してください。</h2>
<%= form_tag top_login_path, method: :post do %>

<%= label_tag :user_address,'アドレス' %>
　<%= text_field_tag :user_address %><br><br>

<%= label_tag :pass, 'パスワード' %>
<%= password_field_tag :pass %><br><br>

<%= submit_tag "ログイン",:id => 'button' %>

<% end %>

<br>
<br>
<div id="button">
<%= link_to "sign up", new_user_path %>
</div>
</p>
</div>