config/routes.rb
Rails.application.routes.draw do

  get 'top/logout'
  post 'top/login'
  get 'top/index'
  
  get 'user/change'
  post 'user/update'

  get 'event/list'
  get 'event/all'
  
  post 'workpartner/tagset'
  get 'workpartner/tagset/:id',to: 'workpartner#tagset'
  get 'workpartner/list'
  get 'workpartner/new'
  get 'workpartner/delete'
  get 'workpartner/tagdelete'
  post 'workpartner/create'
  post 'workpartner/tagcreate'
  
  root 'top#main'

  resources :user
  resources :event
  resources :profile
  

end

app/models/workpartner.rb
class Workpartner < ActiveRecord::Base
      validates :workpartner_name, presence: true
      validates :workpartner_address, presence: true
      
      #belongs_to :profiles
      has_many :users
      has_many :tags
end

app/controllers/workpartner_controller.rb
class WorkpartnerController < ApplicationController
  
  def tagset
    @tag=Tag.new
    p("@tag=", @tag)
    #p("workpartner.id=", workpartner.id)
    #@tags=Tag.where(workpartner_id: params[:workpartner_id])
    @workpartner=Workpartner.find(params[:id])
    p("@workpartner=", @workpartner)
    #tags = Tag.all
    @tags = []
    Tag.all.each do |f|
      if f.workpartner_id == @workpartner.id
        @tags << f
      end
    end
    p("@tags=", @tags)
    
  end
  
  def tagcreate
    @tag = Tag.new(workpartner_tag: params[:tag][:workpartner_tag], workpartner_id: params[:tag][:workpartner_id])
    if @tag.save
      tagsingle=Tag.find_by(workpartner_tag: params[:tag][:workpartner_tag], workpartner_id: params[:tag][:workpartner_id])
      wp=Workpartner.find(params[:tag][:workpartner_id])
      wpall=Workpartner.where(workpartner_address: wp.workpartner_address)
      if wpall.count > 1##ここ
        wpall.each do |e|##
          unless e.id == tagsingle.workpartner_id
            Tag.new(workpartner_tag: params[:tag][:workpartner_tag],workpartner_id: e.id).save
          end
        end
      end
      #redirect_to workpartner_tagset_path(partner_id: params[:tag][:partner_id])
      #redirect_to workpartner_tagset_path
      p("params[:tag][:workpartner_id]",params[:tag][:workpartner_id])
      redirect_to "/workpartner/tagset/#{params[:tag][:workpartner_id]}"
    else
      @tags=Tag.where(workpartner_id: params[:tag][:workpartner_id])
      @workpartner=Workpartner.find(params[:tag][:workpartner_id])
      render 'tagset'
    end
  end
  
  def tagdelete
    tag=Tag.find(params[:id])
    wp=Workpartner.find(tag.workpartner_id)
    wpall=Workpartner.where(workpartner_address: wp.workpartner_address)
    if wpall.count >1
      wpall.each do |e|
        unless e.id == wp.id
          Tag.find_by(workpartner_tag: tag.workpartner_tag,workpartner_id: e.id).destroy
        end
      end
    end
    Tag.find(params[:id]).destroy
    #redirect_to workpartner_tagset_path(partner_id: params[:workpartner_id])
    redirect_to "/workpartner/tagset/#{wp.id}"
  end
  
  def list
    session[:user] = User.find_by(user_address: session[:login_uid])
    p("session[:user]=", session[:user])
    @tags = Tag.all
    p("@tags=", @tags)
    id=User.find_by(user_address: session[:login_uid]).id
    p("id=", id)
    @workpartners = Workpartner.where(user_id: id)
    p("@workpartners=", @workpartners)
  end
  
  def new
    @workpartner=Workpartner.new
  end
  
  def create
    user = User.find_by(user_address: session[:login_uid])
    @workpartner = Workpartner.new(workpartner_name: params[:workpartner][:workpartner_name], 
                                   workpartner_address: params[:workpartner][:workpartner_address], 
                                   user_id: user.id)
    if @workpartner.save
      redirect_to top_index_path
    #id=User.find_by(user_address: session[:login_uid]).id
    #p("id=", id)
    #@workpartner = Workpartner.new(workpartner_name: params[:workpartner][:workpartner_name],
    #                               workpartner_address: params[:workpartner][:workpartner_address],
    #                               user_id: id)
    #if @workpartner.save
    #  if Workpartner.where(workpartner_address: params[:workpartner][:workpartner_address]).count > 1
    #    wptag_id = Workpartner.find_by(workpartner_address: params[:workpartner][:workpartner_address]).id
    #    wpid = Workpartner.find_by(workpartner_address: params[:workpartner][:workpartner_address],user_id: id).id
    #    tags=Tag.where(workpartner_id: wptag_id)
    #    tags.each do |e|
    #      Tag.new(workpartner_tag: e.workpartner_tag,workpartner_id: wpid).save
    #    end
    #  end
    #  redirect_to workpartner_list_path
      
    else
      render 'new'
    end
  end
  
  def delete
    Tag.where(workpartner_id: params[:id]).delete_all
    Workpartner.find(params[:id]).destroy
    redirect_to workpartner_list_path
  end
  
end

app/helpers/workpartner_helper.rb
module WorkpartnerHelper
end

app/views/workpartner/list.html.erb
<div id="head">スケジュールアプリ</div>

<hr>

<div class="main">
<h1>仕事相手一覧表示ページ</h1>
</div>

<div id="button">
<%= link_to "メインページに戻る", root_path %></div><br><br>
<div id="button">
<%= link_to "新しく仕事相手を登録する", workpartner_new_path %></div>

<br><br><hr>

<% @workpartners.each do |f| %>
<div id="workpartner">
  <div class="workpartner">
    NAME:<%= f.workpartner_name %><br>  
    ADDRESS:<%= f.workpartner_address %><br><br>
  
  TAG_ALL:<br>
  <% @tags.each do |g| %>
    <% if f.id == g.workpartner_id %>
    #<%= g.workpartner_tag %>
    <% end %>
  <% end %>
  </div>
  
  
  <div style="text-align:right">
    <div id="tag">
    |<%= link_to 'tag付け', "/workpartner/tagset/#{f.id}" %></div>
    <div id="tag">
    |<%= link_to '削除',  workpartner_delete_path(id: f.id) %></div>
  </div>
  
</div>
  <hr>
<% end %>







<%
=begin
%>
<table border="1">
    <tr>
        <th>名前</th>
        <th>アドレス</th>
        <th>Tagの編集</th>
        <th>削除</th>
        <th>Tagの一覧</th>
    </tr>

<% @workpartners.each do |e| %>

  <tr>
      <td><%= e.workpartner_name %></td>
      <td><%= e.workpartner_address %></td>
      <td><%= link_to '編集', workpartner_tagset_path(partner_id: e.id),method: :post %></td>
      <td><%= link_to '削除',  workpartner_delete_path(id: e.id) %></td>
      <td>
          <% @tags = Tag.where(workpartner_id: e.id) %>
          <% @tags.each do |t| %>
            <%= t.workpartner_tag %>
          <% end %>
      </td>
  </tr>
  
<% end %>

</table>
<%
=end
%>

app/views/workpartner/new.html.erb
<div id="head">スケジュールアプリ</div>

<hr>


<div class="main">
<h1>仕事相手新規登録ページ</h1>
</div>


<div id="button">
<%= link_to "メインページに戻る", top_index_path %></div><br><br>
<div id="button">
<%= link_to "一覧に戻る", workpartner_list_path %></div><br><br>

<div id="workpartner"><h2>
  仕事相手を登録してください。
<% if @workpartner.errors.present? %>
<h3>エラーがあります</h3>
<ul>
	<% @workpartner.errors.full_messages.each do |msg| %>
		<li>
			<%= msg %>
		</li>
	<% end %>
</ul>
<% end %>

<%= form_for @workpartner, :url => {:action => 'create'} do |f| %>

 <%= f.label :workpartner_name, '名前' %>　　
 <%= f.text_field :workpartner_name %><br>
 
 <%= f.label :workpartner_address, 'アドレス' %>
 <%= f.text_field :workpartner_address %><br>
 
 <%= f.submit '登録', :id => 'button' %>
 
<% end %>


</h2></div>

app/views/workpartner/tagset.html.erb
<div id="head">スケジュールアプリ</div>

<hr>


<div class="main">
<h1>仕事相手にTagを設定する</h1>
</div>

<div id="button">
<%= link_to "設定完了(トップへ戻る)", root_path %></div><br><br>
<div id="button">
<%= link_to "一覧に戻る", workpartner_list_path %></div>

<br><br>

<% if @tag.errors.present? %>
<h3>エラーがあります</h3>
<ul>
	<% @tag.errors.full_messages.each do |msg| %>
		<li>
			<%= msg %>
		</li>
	<% end %>
</ul>
<% end %>


<div id="workpartner"><h2>
NAME:<%= @workpartner.workpartner_name %><br>
ADDRESS:<%= @workpartner.workpartner_address %><br><br>

<%= form_for @tag, :url => {:action => 'tagcreate'} do |f| %>
 <%= f.label :workpartner_tag, 'Tagの名前' %>
 <%= f.text_field :workpartner_tag %><br>
 <%= f.hidden_field :workpartner_id, :value => @workpartner.id %>
<%= f.submit 'tagの追加' %>
 
<% end %>
</div>
<hr>
<div id="workpartner">
Tagの一覧<br><br>

<% @tags.each do |f| %>
  #<%= f.workpartner_tag %>
  <%= link_to '×', workpartner_tagdelete_path(id: f.id)%>&ensp;
<% end %>
</h2>
</div>